---
- name: Deploy Matrix
  ansible.builtin.include_role:
    name: common
    tasks_from: docker_service
  vars:
    common_docker_service_name: "Matrix"
    common_docker_service_dir: "{{ matrix_compose_dir }}"
    common_docker_service_compose_template: "{{ playbook_dir }}/roles/matrix/templates/docker-compose.yml.j2"
    common_docker_service_data_dirs:
      - "{{ matrix_data_dir }}"
      - "{{ matrix_data_dir }}/db"
      - "{{ matrix_compose_dir }}"
