eturnal_service_name: "eturnal"
eturnal_image: "ghcr.io/processone/eturnal:latest"

eturnal_config_dir: "{{ docker_config_dir }}/{{ eturnal_service_name }}"

eturnal_domain: "turn.{{ base_domain }}"

eturnal_secret: "{{ vault_eturnal_secret }}"

eturnal_port: "3478"
eturnal_relay_min_port: "49152"
eturnal_relay_max_port: "49200"
