$ANSIBLE_VAULT;1.1;AES256
37306565346362323963333961363630323130376239303763356462653838336661373530303163
3330666131303163643930643665326639333165656132630a383533643966333039313334646237
36643236386661313934346234386634343832393236666339643338663564303637323837333965
3932393239653935630a346233356363383834616537396263333461623639663965366234393865
61356331303636656663396563653362343763323933613039636139373736663930353963353536
66303866326536343136323761383639313863343733346137353630323265333937323939356561
38316235376334626564613333343434653330353563666264393837303131666230363731316262
61366261376531623438363465326636663962386338353265383462333733666137363233393236
65323662306636663931386135323866353564646563613433306565373366336339666637303430
39356339393734393531613863633764633230333233663438616264366132613433373366613361
33653738343938336239323530333435343961366466373839666631623632386432393634346337
32333632653037643230396263653739383635623562343331656232643961373733623239336433
37363935616462316230353163616135346364303863613463303830306436366436313537623132
63626234383935633365626664633964313736623331623961313839393066303931643532656638
35316566393230363335316435666138616632323661366332303262353432313964363933313032
32386631333136616137313336623261613264323233653133323333303233663064383236383938
66346336623537313664643165646134346234663938393532613562393932393137626662356533
33353739323863636432326531373462366262343433653635323538326666336436663937303063
63316231656364613137613630383133366662663738616435623064613964363063316664326133
61636463303266646134626434643765386666356265313562326536663735396264366466353863
61363032643763653030396265656533656237326630343864656361373436666431323734616465
32313837306166386135623066393532666564376464353734333434613232396461396565613032
33616663396264366561626437626564333734623235623338303432316366633132396330386262
62653562323639343566343965356362343439666661613632363466396635396235616135656465
31306266343837376639653563323336353030653762363539303233373863626164393666303437
33366464316139653734326562306566383463666162623261636562653132656561323733373532
34313866636262306462643661376166336432666436323862316234363433393937663333313030
61333631333661663062396531623339336265393961653731373530393935353962376135316439
6534
