---
- name: Ensure Eturnal directory exists
  ansible.builtin.file:
    path: "{{ eturnal_config_dir }}"
    state: directory
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    mode: "0755"
  become: true

- name: Render Eturnal config
  ansible.builtin.template:
    src: eturnal.yml.j2
    dest: "{{ eturnal_config_dir }}/eturnal.yml"
    mode: "0644"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
  become: true

- name: Deploy Eturnal Docker
  ansible.builtin.include_role:
    name: common
    tasks_from: docker_service
  vars:
    common_docker_service_name: "Eturnal"
    common_docker_service_dir: "{{ eturnal_config_dir }}"
    common_docker_service_compose_template: "{{ playbook_dir }}/roles/eturnal/templates/docker-compose.yml.j2"
