---
sablier:
  service: "sablier"

  # Image + Tag
  image: "sablierapp/sablier:latest"

  path: "{{ docker.base_dir }}/sablier"

  # Integration
  # Default to global setting
  socket_proxy: "{{ enable.socket_proxy | default(false) }}"

  # Resources
  memory: "64M"

  # Logging
  log_level: "info"
