---
- name: Validate required variables
  ansible.builtin.assert:
    that:
      - homer.domain is defined
      - deploy_user is defined
    fail_msg: "Required variables missing for Homer"
  tags: [homer, check]

- name: Ensure Homer directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
  loop:
    - "{{ homer.path }}"
    - "{{ homer.assets_dir }}"
  tags: [homer, filesystem]

- name: Render Config (config.yml)
  ansible.builtin.template:
    src: config.yml.j2
    dest: "{{ homer.assets_dir }}/config.yml"
    mode: "0644"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
  register: homer_config
  notify: Restart Homer
  tags: [homer, config]

- name: Render docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ homer.path }}/docker-compose.yml"
    mode: "0640"
    owner: "{{ deploy_user }}"
    group: docker
  register: homer_compose
  notify: Restart Homer
  tags: [homer, config]

- name: Deploy Homer Stack
  community.docker.docker_compose_v2:
    project_src: "{{ homer.path }}"
    state: present
    pull: missing
    remove_orphans: true
    # Пересоздаем, если изменился конфиг (так как он маунтится как volume)
    recreate: "{{ 'always' if (homer_config.changed or homer_compose.changed) else 'auto' }}"
  become: true
  become_user: "{{ deploy_user }}"
  tags: [homer, deploy]
