---
- name: Restart tuwunel
  community.docker.docker_compose_v2:
    project_src: "{{ tuwunel_compose_dir }}"
    state: restarted
  become: true
  become_user: "{{ deploy_user }}"
  listen: restart tuwunel
