---
- name: Create Autoheal directory
  ansible.builtin.file:
    path: /opt/autoheal
    state: directory
    mode: '0755'
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
  become: true  # Создаем под sudo в /opt

- name: Deploy Autoheal compose
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: /opt/autoheal/docker-compose.yml
    mode: '0644'
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
  notify: Restart Autoheal

- name: Start Autoheal
  community.docker.docker_compose_v2:
    project_src: /opt/autoheal
    state: present
  become: true
  become_user: "{{ deploy_user }}"
