---
- name: Deploy Autoheal
  ansible.builtin.include_role:
    name: common
    tasks_from: docker_service
  vars:
    common_docker_service_name: "Autoheal"
    common_docker_service_dir: "/opt/autoheal"
    common_docker_service_compose_template: "{{ playbook_dir }}/roles/autoheal/templates/docker-compose.yml.j2"
