---
- name: Deploy PocketID
  ansible.builtin.include_role:
    name: common
    tasks_from: docker_service
  vars:
    common_docker_service_name: "PocketID"
    common_docker_service_dir: "{{ pocketid_compose_dir }}"
    common_docker_service_compose_template: "{{ playbook_dir }}/roles/pocketid/templates/docker-compose.yml.j2"
    common_docker_service_data_dirs:
      - "{{ pocketid_data_dir }}"
      - "{{ pocketid_data_dir }}/data"
      - "{{ pocketid_compose_dir }}"
