tinyauth_service_name: "tinyauth"
tinyauth_image: "ghcr.io/steveiliop56/tinyauth:v4"

tinyauth_compose_dir: "{{ docker_config_dir }}/{{ tinyauth_service_name }}"

tinyauth_domain: "tinyauth.{{ base_domain }}"
tinyauth_pocketid_public_url: "https://auth.{{ base_domain }}"
tinyauth_pocketid_internal_url: "http://pocketid:1411"

tinyauth_pocketid_client_id: "{{ vault_tinyauth_pocketid_client_id }}"
tinyauth_pocketid_client_secret: "{{ vault_tinyauth_pocketid_client_secret }}"

tinyauth_port: "3000"

tinyauth_auto_redirect: true
