---
hugo:
  service: "hugo"
  builder: "hugo-builder"

  # Paths
  path: "{{ docker.base_dir }}/hugo"
  site_dir: "{{ docker.base_dir }}/hugo/site"
  public_dir: "{{ docker.base_dir }}/shared/hugo"

  # Git Repo
  repo:
    url: "https://github.com/ziix-ru/blog.git"
    version: "main"

  # Network
  domain: "ziix.ru"

  # --- CONTENT CONFIGURATION ---
  content:
    title: "ziix blog"
    author: "ziix"
    theme: "PaperMod"

    # Social Links
    social:
      github: "https://github.com/ziix-ru"
      telegram: "https://t.me/ziix_ru"
      email: "example@ziix.ru"

  # --- COMMENTS (Giscus) ---
  giscus:
    repo: "ziix-ru/blog"
    repo_id: "R_kgDOQkPaEw"
    category_id: "DIC_kwDOQkPaE84Czj8a"

  # --- INTEGRATIONS ---
  autoheal: true
